// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYlPLYUnqBQISt57QHh76nQJ5Oi0EpNeU',
    appId: '1:330946807876:android:2b7c957ac8a622ae931411',
    messagingSenderId: '330946807876',
    projectId: 'grocery-app-39048',
    storageBucket: 'grocery-app-39048.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf5s9BYgTXejOGcP9eZrc_CMojQh3hDII',
    appId: '1:330946807876:web:e1058bc0366b6eb0931411',
    messagingSenderId: '330946807876',
    projectId: 'grocery-app-39048',
    authDomain: 'grocery-app-39048.firebaseapp.com',
    storageBucket: 'grocery-app-39048.firebasestorage.app',
    measurementId: 'G-90CQ47CR9M',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf5s9BYgTXejOGcP9eZrc_CMojQh3hDII',
    appId: '1:330946807876:web:043db4db0900838b931411',
    messagingSenderId: '330946807876',
    projectId: 'grocery-app-39048',
    authDomain: 'grocery-app-39048.firebaseapp.com',
    storageBucket: 'grocery-app-39048.firebasestorage.app',
    measurementId: 'G-WFZ3QLQZ5D',
  );

}